apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1 # required no. of podsfor a partivular image
  selector:
    matchLabels:
      app: client # tell deployment to find pod with these lables and manage them only
  template: # configurations for the pod
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ronin211/client  # auto specify to latest version
##creaeting cluster ip service for client
##creaeting cluster ip service for client
#use --- to separate different objects
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
      
